name: "Delete all tags in a repository"
description: "Delete all tags in repository"
author: "yhvardhan@gmail.com"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0

    - name: Setup Go environment
      uses: actions/setup-go@v5.0.2
      with:
        go-version: '1.23.0'

    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}/cmd && go get .

    - name: Delete All Tags
      shell: bash
      run: go run delete_all_tags.go
      id: delete_all_tags
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GRAPHQL_ENDPOINT: ${{ github.graphql_url }}
        OWNER: ${{ github.repository_owner }}
        REPOSITORY: ${{ github.repository }}
        ENTERPRISE_URL: ${{ github.server_url }}

